# Generated by Django 5.0.8 on 2024-08-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categroy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categroy',
            name='post',
        ),
    ]
