# Generated by Django 5.0.8 on 2024-08-11 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_categroy_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categroy',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.post'),
        ),
    ]
