# Generated by Django 5.0.8 on 2024-08-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_categroy_post_categroy_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categroy',
            name='post',
        ),
    ]
