# Generated by Django 5.0.8 on 2024-08-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categroy',
            name='title',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
