# Generated by Django 5.0.8 on 2024-08-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontactus',
            name='location',
            field=models.TextField(default='None'),
        ),
    ]
